import type { Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'style',
    title: 'سبک هنری (Art Style)',
    type: 'simple',
    options: [
      { label: 'فتورئالیستیک', value: 'photorealistic', description: 'ایجاد تصویری با جزئیات بسیار بالا، شبیه به یک عکس واقعی.', previewImageUrl: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'هنر دیجیتال', value: 'digital art', description: 'تصویری که با ابزارهای دیجیتال مانند تبلت گرافیکی خلق شده است.', previewImageUrl: 'https://images.pexels.com/photos/1964467/pexels-photo-1964467.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'نقاشی رنگ روغن', value: 'oil painting', description: 'شبیه‌سازی بافت و ظاهر نقاشی‌های کلاسیک با رنگ روغن.', previewImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg' },
      { label: 'نقاشی آبرنگ', value: 'watercolor painting', description: 'شبیه‌سازی تکنیک نقاشی با آبرنگ که شفافیت و لطافت خاصی دارد.', previewImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/16/JMW_Turner_-_The_Blue_Rigi%2C_Sunrise.jpg' },
      { label: 'طراحی با زغال', value: 'charcoal drawing', description: 'شبیه‌سازی طراحی با زغال که کنتراست بالا و بافتی خشن دارد.', previewImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Portrait_of_a_man_in_charcoal_by_John_Singer_Sargent_1910.jpg' },
      { label: 'امپرسیونیسم', value: 'impressionism', description: 'سبکی با ضربات قلم کوتاه و قابل مشاهده و تاکید بر نور.', previewImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Claude_Monet%2C_Impression%2C_soleil_levant.jpg/1280px-Claude_Monet%2C_Impression%2C_soleil_levant.jpg' },
      { label: 'سبک انیمه', value: 'anime style', description: 'سبک بصری انیمیشن‌های ژاپنی با چشمان درشت و رنگ‌های زنده.', previewImageUrl: 'https://images.pexels.com/photos/10530424/pexels-photo-10530424.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'پیکسل آرت', value: 'pixel art', description: 'هنر دیجیتال که در آن تصاویر در سطح پیکسل ویرایش می‌شوند.', previewImageUrl: 'https://images.pexels.com/photos/17912441/pexels-photo-17912441/free-photo-of-pixel-art-of-city-street-at-night.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'هنر مفهومی', value: 'concept art', description: 'طراحی اولیه برای انتقال ایده و حس و حال یک اثر هنری.', previewImageUrl: 'https://images.pexels.com/photos/7319114/pexels-photo-7319114.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'سورئالیسم', value: 'surrealism', description: 'سبکی که صحنه‌های عجیب و غیرمنطقی شبیه به رویا را به تصویر می‌کشد.', previewImageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg' },
      { label: 'مینیمالیسم', value: 'minimalist', description: 'استفاده از حداقل عناصر و سادگی برای انتقال پیام.', previewImageUrl: 'https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?q=80&w=2670&auto=format&fit=crop' },
      { label: 'مدل سه‌بعدی', value: '3D model', description: 'ایجاد تصویری که به نظر می‌رسد با نرم‌افزارهای مدلسازی سه‌بعدی ساخته شده است.', previewImageUrl: 'https://images.pexels.com/photos/2377164/pexels-photo-2377164.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'پلیگان پایین (Low Poly)', value: 'low poly', description: 'سبکی سه‌بعدی که از تعداد کمی چندضلعی برای ایجاد ظاهری ساده و هندسی استفاده می‌کند.', previewImageUrl: 'https://images.pexels.com/photos/20967/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'هنر گرافیتی', value: 'graffiti art', description: 'سبک هنر خیابانی با رنگ‌های تند و فرم‌های پویا.', previewImageUrl: 'https://images.pexels.com/photos/163064/play-stone-network-networked-interactive-163064.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'سبک گوتیک', value: 'gothic art', description: 'سبکی تاریک و دراماتیک با معماری نوک‌تیز و جزئیات فراوان.', previewImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Notre-Dame_de_Paris_2013-05-24.jpg/1024px-Notre-Dame_de_Paris_2013-05-24.jpg' },
      { label: 'آرت نوو', value: 'art nouveau', description: 'سبکی تزئینی با خطوط منحنی و روان و الهام از طبیعت.', previewImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Alfons_Mucha_-_Zodiac.jpg/800px-Alfons_Mucha_-_Zodiac.jpg' },
      { label: 'باهاوس', value: 'bauhaus style', description: 'سبکی مدرن با تمرکز بر سادگی، اشکال هندسی و کارکردگرایی.', previewImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Staatliches_Bauhaus_Weimar_Ausstellung_1923.jpg/800px-Staatliches_Bauhaus_Weimar_Ausstellung_1923.jpg' },
      { label: 'استیم‌پانک', value: 'steampunk', description: 'سبکی علمی-تخیلی که فناوری مدرن را با ماشین‌آلات بخار دوره ویکتوریا ترکیب می‌کند.', previewImageUrl: 'https://images.pexels.com/photos/1036841/pexels-photo-1036841.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'سایبرپانک', value: 'cyberpunk', description: 'سبکی آینده‌نگرانه و تاریک با فناوری‌های پیشرفته، نئون و تضادهای اجتماعی.', previewImageUrl: 'https://images.pexels.com/photos/4009409/pexels-photo-4009409.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
      { label: 'ویپورویو', value: 'vaporwave', description: 'سبکی نوستالژیک با الهام از زیبایی‌شناسی دهه ۸۰ و ۹۰ میلادی، مجسمه‌های رومی و رنگ‌های نئونی.', previewImageUrl: 'https://images.pexels.com/photos/7476834/pexels-photo-7476834.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
    ],
  },
  {
    id: 'cameraAngle',
    title: 'زاویه دوربین (Camera Angle)',
    type: 'multi-select-grouped',
    subCategories: [
      {
        title: 'نوع نما (Shot Type)',
        selectionType: 'single',
        options: [
          { label: 'نمای بسیار نزدیک (ECU)', value: 'extreme close-up shot', description: 'نمایی بسیار نزدیک که تنها بخشی از چهره یا یک شیء کوچک را نشان می‌دهد.' },
          { label: 'نمای نزدیک (CU)', value: 'close-up shot', description: 'نمایی که معمولاً سر و شانه‌های سوژه را در کادر قرار می‌دهد.' },
          { label: 'نمای متوسط نزدیک (MCU)', value: 'medium close-up shot', description: 'نمایی از نیم‌تنه بالای سوژه، از سینه به بالا.' },
          { label: 'نمای کابوی', value: 'cowboy shot', description: 'نمایی از وسط ران به بالا، که در فیلم‌های وسترن محبوب بود.' },
          { label: 'نمای متوسط (MS)', value: 'medium shot', description: 'نمایی که سوژه را تقریباً از کمر به بالا نشان می‌دهد.' },
          { label: 'نمای کامل (FS)', value: 'full shot', description: 'نمایی که تمام قد سوژه را از سر تا پا در کادر جای می‌دهد.' },
          { label: 'نمای دور (LS)', value: 'long shot', description: 'نمایی که سوژه را به طور کامل در محیط اطرافش نشان می‌دهد.' },
          { label: 'نمای بسیار دور (ELS)', value: 'extreme long shot', description: 'نمایی بسیار دور که در آن سوژه بخش کوچکی از منظره است.' },
        ],
      },
      {
        title: 'زاویه (Angle)',
        selectionType: 'single',
        options: [
          { label: 'هم‌سطح چشم', value: 'eye-level shot', description: 'دوربین در سطح چشم سوژه قرار دارد و حس طبیعی ایجاد می‌کند.' },
          { label: 'زاویه از بالا', value: 'high-angle shot', description: 'دوربین بالاتر از سوژه قرار دارد و آن را کوچک یا ضعیف نشان می‌دهد.' },
          { label: 'زاویه از پایین', value: 'low-angle shot', description: 'دوربین پایین‌تر از سوژه قرار دارد و آن را قدرتمند یا بزرگ نشان می‌دهد.' },
          { label: 'دید پرنده', value: "bird's-eye view", description: 'نمایی از بالا که مستقیماً به سمت پایین نگاه می‌کند.' },
          { label: 'دید کرم', value: "worm's-eye view", description: 'نمایی از پایین که مستقیماً به سمت بالا نگاه می‌کند.' },
          { label: 'زاویه هلندی', value: 'dutch angle', description: 'کج کردن دوربین برای ایجاد حس تنش، بی‌ثباتی یا هیجان.' },
          { label: 'نمای روی شانه', value: 'over-the-shoulder shot', description: 'نمایی از پشت شانه یک شخصیت که به سوژه دیگری نگاه می‌کند.' },
        ],
      },
      {
        title: 'لنز و جزئیات (Lens & Details)',
        selectionType: 'multiple',
        options: [
          { label: 'لنز واید', value: 'wide-angle lens', description: 'فضای بیشتری را در کادر جای می‌دهد و ممکن است در لبه‌ها اعوجاج ایجاد کند.' },
          { label: 'لنز تله‌فوتو', value: 'telephoto lens', description: 'سوژه‌های دور را نزدیک می‌کند و پس‌زمینه را فشرده می‌سازد.' },
          { label: 'لنز چشم‌ماهی', value: 'fisheye lens', description: 'یک لنز واید شدید که تصویری کروی و تحریف‌شده ایجاد می‌کند.' },
          { label: 'عمق میدان کم', value: 'shallow depth of field', description: 'سوژه اصلی در فوکوس و پس‌زمینه کاملاً تار می‌شود.' },
          { label: 'بوکه', value: 'bokeh', description: 'کیفیت زیبایی‌شناختی تاری در بخش‌های خارج از فوکوس تصویر.' },
          { label: 'فِلِر لنز', value: 'lens flare', description: 'ایجاد هاله‌های نورانی در تصویر هنگام تابش مستقیم نور به لنز.' },
          { label: 'فوکوس نرم', value: 'soft focus', description: 'ایجاد یک تاری ملایم و رویایی در کل تصویر.' },
        ],
      },
    ],
  },
  {
    id: 'facialExpression',
    title: 'حالت چهره (Facial Expression)',
    type: 'simple',
    options: [
      { label: 'خوشحال', value: 'happy' },
      { label: 'خندان', value: 'smiling' },
      { label: 'غمگین', value: 'sad' },
      { label: 'گریه کردن', value: 'crying' },
      { label: 'عصبانی', value: 'angry' },
      { label: 'فریاد زدن', value: 'shouting' },
      { label: 'متعجب', value: 'surprised' },
      { label: 'ترسیده', value: 'scared' },
      { label: 'جدی', value: 'serious expression' },
      { label: 'متفکر', value: 'thoughtful expression' },
      { label: 'متمرکز', value: 'focused expression' },
      { label: 'مصمم', value: 'determined expression' },
      { label: 'در حال صحبت', value: 'talking' },
      { label: 'چشمک زدن', value: 'winking' },
      { label: 'ناز / کیوت', value: 'cute expression' },
      { label: 'شیطنت آمیز', value: 'mischievous expression' },
      { label: 'پوزخند زدن', value: 'smirking' },
      { label: 'عشوه گر', value: 'flirty expression' },
      { label: 'گیج', value: 'puzzled' },
      { label: 'شکاک', value: 'skeptical expression' },
      { label: 'بی حوصله', value: 'bored expression' },
      { label: 'خمیازه کشیدن', value: 'yawning' },
      { label: 'خجالتی', value: 'shy expression' },
      { label: 'راضی', value: 'content expression' },
    ],
  },
  {
    id: 'pose',
    title: 'حالت سوژه نسبت به دوربین (Pose)',
    type: 'simple',
    options: [
      { label: 'رو به دوربین', value: 'facing the camera' },
      { label: 'پشت به دوربین', value: 'from behind' },
      { label: 'نیمرخ', value: 'profile view' },
      { label: 'سه رخ', value: 'three-quarters view' },
      { label: 'نگاه به دوربین', value: 'looking at viewer' },
      { label: 'نگاه به دوردست', value: 'looking away' },
      { label: 'ایستاده', value: 'standing' },
      { label: 'دست به سینه', value: 'arms crossed' },
      { label: 'دست به کمر', value: 'hands on hips' },
      { label: 'دست در جیب', value: 'hands in pockets' },
      { label: 'تکیه داده', value: 'leaning against something' },
      { label: 'نشسته', value: 'sitting' },
      { label: 'چهارزانو', value: 'sitting cross-legged' },
      { label: 'لم داده', value: 'lounging' },
      { label: 'زانو زده', value: 'kneeling' },
      { label: 'چمباتمه زده', value: 'crouching' },
      { label: 'خوابیده', value: 'lying down' },
      { label: 'در حال خواب', value: 'sleeping' },
      { label: 'راه رفتن', value: 'walking' },
      { label: 'دویدن', value: 'running' },
      { label: 'پریدن', value: 'jumping' },
      { label: 'رقصیدن', value: 'dancing' },
      { label: 'در حال کشش', value: 'stretching' },
      { label: 'ژست یوگا', value: 'yoga pose' },
      { label: 'حالت مبارزه', value: 'fighting stance' },
      { label: 'دست تکان دادن', value: 'waving' },
      { label: 'دست روی سر', value: 'hands on head' },
      { label: 'اشاره کردن', value: 'pointing' },
      { label: 'بازوهای کشیده', value: 'arms outstretched' },
      { label: 'خم شدن به جلو', value: 'bending forward' },
      { label: 'زانو در بغل', value: 'hugging knees' },
      { label: 'در حال مدیتیشن', value: 'meditating' },
    ],
  },
  {
    id: 'lighting',
    title: 'نورپردازی (Lighting)',
    type: 'simple',
    options: [
      { label: 'نورپردازی سینمایی', value: 'cinematic lighting', description: 'نورپردازی با کنتراست بالا و حس و حال سینمایی، مناسب برای صحنه‌های دراماتیک.' },
      { label: 'نورپردازی دراماتیک', value: 'dramatic lighting', description: 'استفاده از سایه‌های تند و تضاد نوری برای ایجاد هیجان و تنش.' },
      { label: 'نورپردازی فیلم نوآر', value: 'film noir lighting', description: 'نورپردازی با کنتراست بالا و سایه‌های عمیق، الهام گرفته از فیلم‌های کلاسیک نوآر.' },
      { label: 'نور ملایم', value: 'soft light', description: 'نوری یکنواخت و پخش‌شده که سایه‌های نرمی ایجاد می‌کند.' },
      { label: 'نور سخت', value: 'hard light', description: 'نوری مستقیم و متمرکز که سایه‌های تند و مشخصی ایجاد می‌کند.' },
      { label: 'نور استودیویی', value: 'studio lighting', description: 'نورپردازی کنترل‌شده و حرفه‌ای با استفاده از چندین منبع نور.' },
      { label: 'نور لبه‌ای (Rim)', value: 'rim lighting', description: 'یک منبع نور در پشت سوژه که هاله‌ای نورانی دور لبه‌های آن ایجاد می‌کند.' },
      { label: 'ضد نور (سیلوئت)', value: 'backlighting, silhouette', description: 'قرار دادن منبع نور پشت سوژه تا فقط سایه‌ای تاریک از آن مشخص باشد.' },
      { label: 'ساعت طلایی', value: 'golden hour lighting', description: 'نور گرم و طلایی خورشید در زمان طلوع و غروب.' },
      { label: 'ساعت آبی', value: 'blue hour lighting', description: 'نور نرم و سرد در زمان گرگ و میش، قبل از طلوع یا بعد از غروب خورشید.' },
      { label: 'نور مهتاب', value: 'moonlight', description: 'نورپردازی ملایم و سرد که صحنه‌های شبانه را تداعی می‌کند.' },
      { label: 'نور نئون', value: 'neon lighting', description: 'استفاده از نورهای نئونی رنگارنگ برای ایجاد فضایی مدرن یا سایبرپانک.' },
      { label: 'نور حجمی', value: 'volumetric lighting', description: 'نورپردازی که در آن پرتوهای نور در هوا (مثلاً در مه یا دود) قابل مشاهده هستند.' },
      { label: 'پرتوهای الهی', value: 'god rays, crepuscular rays', description: 'پرتوهای نوری که از میان ابرها یا موانع عبور کرده و در هوا دیده می‌شوند.' },
      { label: 'کیاروسکورو', value: 'chiaroscuro', description: 'تضاد شدید بین نور و تاریکی برای ایجاد عمق و درام، الهام گرفته از نقاشی‌های رنسانس.' },
      { label: 'نورپردازی زیر آب', value: 'underwater lighting', description: 'نورپردازی پراکنده و موج‌دار که حس غوطه‌وری در آب را ایجاد می‌کند.' },
      { label: 'درخشش زیست‌تابی', value: 'bioluminescent glow', description: 'نور ملایم و جادویی که از موجودات زنده یا گیاهان خیالی ساطع می‌شود.' },
      { label: 'نور شمع', value: 'candlelight', description: 'نور گرم و لرزان شمع که فضایی صمیمی یا قدیمی ایجاد می‌کند.' },
      { label: 'نورپردازی سوزاننده', value: 'caustic lighting', description: 'الگوهای نوری زیبایی که در اثر شکست یا بازتاب نور از سطح آب ایجاد می‌شود.' },
    ],
  },
  {
    id: 'colorPalette',
    title: 'پالت رنگی (Color Palette)',
    type: 'simple',
    options: [
      { label: 'رنگ‌های زنده و اشباع', value: 'vibrant, saturated colors', description: 'استفاده از رنگ‌های شاد، پرانرژی و بسیار غلیظ.' },
      { label: 'رنگ‌های پاستلی', value: 'pastel colors', description: 'رنگ‌های ملایم و کم‌رنگ با اشباع پایین، مانند صورتی روشن یا آبی آسمانی.' },
      { label: 'پالت تیره و رازآلود', value: 'dark and moody palette', description: 'استفاده از رنگ‌های تیره و سایه‌ها برای ایجاد فضایی مرموز و دراماتیک.' },
      { label: 'پالت روشن و دلباز', value: 'light and airy palette', description: 'استفاده از رنگ‌های روشن و سفید برای ایجاد حسی از باز بودن و آرامش.' },
      { label: 'کنتراست بالا', value: 'high contrast', description: 'تضاد شدید بین رنگ‌های روشن و تیره برای جلب توجه و ایجاد قدرت بصری.' },
      { label: 'کنتراست پایین', value: 'low contrast', description: 'استفاده از رنگ‌های نزدیک به هم برای ایجاد فضایی آرام و یکپارچه.' },
      { label: 'تک‌رنگ (مونوکروم)', value: 'monochromatic', description: 'استفاده از سایه‌ها و تنالیته‌های مختلف تنها یک رنگ.' },
      { label: 'سیاه و سفید', value: 'black and white', description: 'تصویر بدون رنگ که تنها از طیف خاکستری، سیاه و سفید استفاده می‌کند.' },
      { label: 'پالت سینمایی نارنجی و فیروزه‌ای', value: 'cinematic teal and orange', description: 'پالت رنگی بسیار محبوب در فیلم‌ها که در آن رنگ پوست با پس‌زمینه سرد تضاد دارد.' },
      { label: 'رنگ‌های مکمل', value: 'complementary colors', description: 'استفاده از رنگ‌های متضاد در چرخه رنگ (مانند قرمز و سبز) برای ایجاد کنتراست بالا.' },
      { label: 'رنگ‌های مشابه', value: 'analogous colors', description: 'استفاده از رنگ‌های هم‌جوار در چرخه رنگ (مانند زرد، سبز و آبی) برای ایجاد هماهنگی.' },
      { label: 'پالت سایبرپانک', value: 'cyberpunk color palette', description: 'ترکیبی از رنگ‌های نئونی تند مانند صورتی، آبی و بنفش در پس‌زمینه‌ای تاریک.' },
      { label: 'پالت رترو', value: 'retro color palette', description: 'رنگ‌های نوستالژیک الهام گرفته از دهه‌های ۶۰، ۷۰ یا ۸۰ میلادی.' },
      { label: 'رنگ‌های خاکی', value: 'earth tones', description: 'رنگ‌های الهام گرفته از طبیعت مانند قهوه‌ای، سبز زیتونی و بژ.' },
      { label: 'رنگ‌های درخشان', value: 'iridescent colors', description: 'رنگ‌هایی که با تغییر زاویه دید تغییر می‌کنند، مانند رنگین‌کمان روی حباب صابون.' },
      { label: 'سپیا', value: 'sepia tones', description: 'افکتی که به تصاویر سیاه و سفید ته‌رنگ قهوه‌ای می‌دهد تا ظاهری قدیمی پیدا کنند.' },
    ],
  },
  {
    id: 'specificColors',
    title: 'انتخاب رنگ‌های خاص (Specific Colors)',
    type: 'color-grid',
    groups: [
        {
            title: 'قرمزها و صورتی‌ها',
            options: [
                { label: 'Red', value: 'red', hex: '#FF0000', description: 'قرمز' },
                { label: 'Crimson', value: 'crimson', hex: '#DC143C', description: 'قرمز تیره' },
                { label: 'Scarlet', value: 'scarlet', hex: '#FF2400', description: 'قرمز روشن' },
                { label: 'Ruby', value: 'ruby', hex: '#E0115F', description: 'قرمز یاقوتی' },
                { label: 'Carmine', value: 'carmine', hex: '#960018', description: 'قرمز کارمین' },
                { label: 'Maroon', value: 'maroon', hex: '#800000', description: 'زرشکی' },
                { label: 'Burgundy', value: 'burgundy', hex: '#800020', description: 'شرابی' },
                { label: 'Raspberry', value: 'raspberry', hex: '#E30B5D', description: 'تمشکی' },
                { label: 'Pink', value: 'pink', hex: '#FFC0CB', description: 'صورتی' },
                { label: 'Hot Pink', value: 'hot pink', hex: '#FF69B4', description: 'صورتی جیغ' },
                { label: 'Deep Pink', value: 'deep pink', hex: '#FF1493', description: 'صورتی تیره' },
                { label: 'Magenta', value: 'magenta', hex: '#FF00FF', description: 'سرخابی' },
                { label: 'Rose', value: 'rose', hex: '#FF66CC', description: 'صورتی گلی' },
            ]
        },
        {
            title: 'نارنجی‌ها',
            options: [
                { label: 'Orange', value: 'orange', hex: '#FFA500', description: 'نارنجی' },
                { label: 'Dark Orange', value: 'dark orange', hex: '#FF8C00', description: 'نارنجی تیره' },
                { label: 'Burnt Orange', value: 'burnt orange', hex: '#CC5500', description: 'نارنجی سوخته' },
                { label: 'Tangerine', value: 'tangerine', hex: '#F28500', description: 'نارنگی' },
                { label: 'Coral', value: 'coral', hex: '#FF7F50', description: 'مرجانی' },
                { label: 'Salmon', value: 'salmon', hex: '#FA8072', description: 'صورتی ماهی سالمون' },
                { label: 'Apricot', value: 'apricot', hex: '#FBCEB1', description: 'زردآلویی' },
                { label: 'Peach', value: 'peach', hex: '#FFE5B4', description: 'هلویی' },
                { label: 'Ochre', value: 'ochre', hex: '#CC7722', description: 'اخرایی' },
                { label: 'Rust', value: 'rust', hex: '#B7410E', description: 'زنگاری' },
                { label: 'Mango', value: 'mango', hex: '#FDBE02', description: 'انبه‌ای' },
            ]
        },
        {
            title: 'زردها',
            options: [
                { label: 'Yellow', value: 'yellow', hex: '#FFFF00', description: 'زرد' },
                { label: 'Lemon', value: 'lemon', hex: '#FFF44F', description: 'لیموئی' },
                { label: 'Mustard', value: 'mustard', hex: '#FFDB58', description: 'خردلی' },
                { label: 'Saffron', value: 'saffron', hex: '#F4C430', description: 'زعفرانی' },
                { label: 'Amber', value: 'amber', hex: '#FFBF00', description: 'کهربایی' },
                { label: 'Gold', value: 'gold', hex: '#FFD700', description: 'طلایی' },
                { label: 'Canary Yellow', value: 'canary yellow', hex: '#FFEF00', description: 'زرد قناری' },
                { label: 'Cream', value: 'cream', hex: '#FFFDD0', description: 'کرم' },
                { label: 'Ivory', value: 'ivory', hex: '#FFFFF0', description: 'عاجی' },
                { label: 'Chartreuse', value: 'chartreuse', hex: '#DFFF00', description: 'سبز چارتریوس' },
            ]
        },
        {
            title: 'سبزها',
            options: [
                { label: 'Green', value: 'green', hex: '#008000', description: 'سبز' },
                { label: 'Lime', value: 'lime', hex: '#00FF00', description: 'سبز لیمویی روشن' },
                { label: 'Forest Green', value: 'forest green', hex: '#228B22', description: 'سبز جنگلی' },
                { label: 'Emerald', value: 'emerald', hex: '#50C878', description: 'سبز زمردی' },
                { label: 'Olive', value: 'olive', hex: '#808000', description: 'سبز زیتونی' },
                { label: 'Moss Green', value: 'moss green', hex: '#8A9A5B', description: 'سبز خزه‌ای' },
                { label: 'Jade', value: 'jade', hex: '#00A86B', description: 'سبز یشمی' },
                { label: 'Sage', value: 'sage green', hex: '#B2AC88', description: 'سبز مریم گلی' },
                { label: 'Kelly Green', value: 'kelly green', hex: '#4CBB17', description: 'سبز کلی' },
                { label: 'Hunter Green', value: 'hunter green', hex: '#355E3B', description: 'سبز شکاری' },
            ]
        },
        {
            title: 'فیروزه‌ای‌ها و سبزآبی‌ها',
            options: [
                { label: 'Teal', value: 'teal', hex: '#008080', description: 'سبزآبی' },
                { label: 'Cyan', value: 'cyan', hex: '#00FFFF', description: 'فیروزه‌ای' },
                { label: 'Aqua', value: 'aqua', hex: '#00FFFF', description: 'آبی دریایی' },
                { label: 'Turquoise', value: 'turquoise', hex: '#40E0D0', description: 'فیروزه‌ای روشن' },
                { label: 'Aquamarine', value: 'aquamarine', hex: '#7FFFD4', description: 'سبزآبی روشن' },
                { label: 'Sea Green', value: 'sea green', hex: '#2E8B57', description: 'سبز دریایی' },
                { label: 'Verdigris', value: 'verdigris', hex: '#43B3AE', description: 'زنگاری' },
            ]
        },
        {
            title: 'آبی‌ها',
            options: [
                { label: 'Blue', value: 'blue', hex: '#0000FF', description: 'آبی' },
                { label: 'Sky Blue', value: 'sky blue', hex: '#87CEEB', description: 'آبی آسمانی' },
                { label: 'Royal Blue', value: 'royal blue', hex: '#4169E1', description: 'آبی سلطنتی' },
                { label: 'Navy Blue', value: 'navy blue', hex: '#000080', description: 'سرمه‌ای' },
                { label: 'Sapphire', value: 'sapphire', hex: '#0F52BA', description: 'آبی یاقوتی' },
                { label: 'Azure', value: 'azure', hex: '#007FFF', description: 'لاجوردی' },
                { label: 'Cobalt', value: 'cobalt blue', hex: '#0047AB', description: 'آبی کبالت' },
                { label: 'Ultramarine', value: 'ultramarine', hex: '#120A8F', description: 'آبی پررنگ' },
                { label: 'Periwinkle', value: 'periwinkle', hex: '#CCCCFF', description: 'آبی مایل به بنفش' },
            ]
        },
        {
            title: 'بنفش‌ها',
            options: [
                { label: 'Purple', value: 'purple', hex: '#800080', description: 'بنفش' },
                { label: 'Indigo', value: 'indigo', hex: '#4B0082', description: 'نیلی' },
                { label: 'Violet', value: 'violet', hex: '#EE82EE', description: 'بنفش روشن' },
                { label: 'Royal Purple', value: 'royal purple', hex: '#7851A9', description: 'ارغوانی سلطنتی' },
                { label: 'Amethyst', value: 'amethyst', hex: '#9966CC', description: 'بنفش آمتیست' },
                { label: 'Plum', value: 'plum', hex: '#DDA0DD', description: 'آلویی' },
                { label: 'Mauve', value: 'mauve', hex: '#E0B0FF', description: 'بنفش مایل به صورتی' },
                { label: 'Fuchsia', value: 'fuchsia', hex: '#FF00FF', description: 'سرخابی' },
            ]
        },
        {
            title: 'قهوه‌ای‌ها و خاکی',
            options: [
                { label: 'Brown', value: 'brown', hex: '#964B00', description: 'قهوه‌ای' },
                { label: 'Chocolate', value: 'chocolate', hex: '#D2691E', description: 'قهوه‌ای شکلاتی' },
                { label: 'Sienna', value: 'sienna', hex: '#A0522D', description: 'قهوه‌ای مایل به قرمز' },
                { label: 'Umber', value: 'umber', hex: '#635147', description: 'قهوه‌ای سوخته' },
                { label: 'Tan', value: 'tan', hex: '#D2B48C', description: 'قهوه‌ای روشن' },
                { label: 'Khaki', value: 'khaki', hex: '#C3B091', description: 'خاکی' },
                { label: 'Sepia', value: 'sepia', hex: '#704214', description: 'سپیا' },
            ]
        },
        {
            title: 'خنثی‌ها و خاکستری‌ها',
            options: [
                { label: 'White', value: 'white', hex: '#FFFFFF', description: 'سفید' },
                { label: 'Beige', value: 'beige', hex: '#F5F5DC', description: 'بژ' },
                { label: 'Gray', value: 'gray', hex: '#808080', description: 'خاکستری' },
                { label: 'Charcoal', value: 'charcoal', hex: '#36454F', description: 'خاکستری زغالی' },
                { label: 'Slate Gray', value: 'slate gray', hex: '#708090', description: 'خاکستری سنگی' },
                { label: 'Black', value: 'black', hex: '#000000', description: 'سیاه' },
            ]
        },
        {
            title: 'متالیک و اکلیلی',
            options: [
                { label: 'Gold', value: 'metallic gold', hex: 'linear-gradient(135deg, #FFD700, #DAA520, #B8860B)', description: 'طلایی متالیک' },
                { label: 'Silver', value: 'silver', hex: 'linear-gradient(135deg, #EAEAEA, #C0C0C0, #A9A9A9)', description: 'نقره‌ای' },
                { label: 'Bronze', value: 'bronze', hex: 'linear-gradient(135deg, #CD7F32, #A0522D, #8B4513)', description: 'برنزی' },
                { label: 'Copper', value: 'copper', hex: 'linear-gradient(135deg, #B87333, #D2691E, #A0522D)', description: 'مسی' },
                { label: 'Platinum', value: 'platinum', hex: 'linear-gradient(135deg, #F5F5F5, #E5E4E2, #D1D0CE)', description: 'پلاتینیوم' },
                { label: 'Rose Gold', value: 'rose gold', hex: 'linear-gradient(135deg, #EBC0B1, #B76E79, #A35D6A)', description: 'رزگلد' },
                { label: 'Glitter Gold', value: 'gold glitter', hex: 'radial-gradient(circle, #FFFDE4 0%, #FFD700 30%, #F0E68C 70%, #BDB76B 100%)', description: 'طلایی اکلیلی' },
                { label: 'Glitter Silver', value: 'silver glitter', hex: 'radial-gradient(circle, #FFFFFF 0%, #E0E0E0 30%, #C0C0C0 70%, #A9A9A9 100%)', description: 'نقره‌ای اکلیلی' },
                { label: 'Glitter Rose Gold', value: 'rose gold glitter', hex: 'radial-gradient(circle, #FFE4E1 0%, #EBC0B1 30%, #B76E79 70%, #D8BFD8 100%)', description: 'رزگلد اکلیلی' },
                { label: 'Iridescent Pearl', value: 'iridescent pearl', hex: 'linear-gradient(135deg, #F0F8FF, #FAEBD7, #FFF0F5, #E6E6FA)', description: 'مرواریدی رنگین‌کمانی' },
            ]
        },
        {
            title: 'پاستلی',
            options: [
                { label: 'Pastel Pink', value: 'pastel pink', hex: '#FFD1DC', description: 'صورتی پاستلی' },
                { label: 'Pastel Peach', value: 'pastel peach', hex: '#FFCBA4', description: 'هلویی پاستلی' },
                { label: 'Pastel Orange', value: 'pastel orange', hex: '#FFDAB9', description: 'نارنجی پاستلی' },
                { label: 'Pastel Yellow', value: 'pastel yellow', hex: '#FDFD96', description: 'زرد پاستلی' },
                { label: 'Pastel Green', value: 'pastel green', hex: '#C1E1C1', description: 'سبز پاستلی' },
                { label: 'Mint', value: 'mint', hex: '#98FF98', description: 'سبز نعنایی' },
                { label: 'Pastel Blue', value: 'pastel blue', hex: '#AEC6CF', description: 'آبی پاستلی' },
                { label: 'Baby Blue', value: 'baby blue', hex: '#89CFF0', description: 'آبی بچگانه' },
                { label: 'Periwinkle', value: 'periwinkle', hex: '#CCCCFF', description: 'پریوینکل' },
                { label: 'Lavender', value: 'lavender', hex: '#E6E6FA', description: 'اسطوخودوسی' },
                { label: 'Pastel Purple', value: 'pastel purple', hex: '#B39EB5', description: 'بنفش پاستلی' },
                { label: 'Mauve', value: 'mauve', hex: '#E0B0FF', description: 'بنفش mauve' },
            ]
        },
        {
            title: 'نئون',
            options: [
                { label: 'Neon Red', value: 'neon red', hex: '#FF073A', description: 'قرمز نئونی' },
                { label: 'Neon Pink', value: 'neon pink', hex: '#FF007F', description: 'صورتی نئونی' },
                { label: 'Neon Orange', value: 'neon orange', hex: '#FF5F1F', description: 'نارنجی نئونی' },
                { label: 'Neon Yellow', value: 'neon yellow', hex: '#FFF01F', description: 'زرد نئونی' },
                { label: 'Electric Lime', value: 'electric lime', hex: '#CCFF00', description: 'لیمویی الکتریکی' },
                { label: 'Neon Green', value: 'neon green', hex: '#39FF14', description: 'سبز نئونی' },
                { label: 'Neon Cyan', value: 'neon cyan', hex: '#00FFFF', description: 'فیروزه‌ای نئونی' },
                { label: 'Electric Blue', value: 'electric blue', hex: '#7DF9FF', description: 'آبی الکتریکی' },
                { label: 'Neon Blue', value: 'neon blue', hex: '#1F51FF', description: 'آبی نئونی' },
                { label: 'Neon Purple', value: 'neon purple', hex: '#BC13FE', description: 'بنفش نئونی' },
                { label: 'Neon Magenta', value: 'neon magenta', hex: '#FF00FF', description: 'سرخابی نئونی' },
            ]
        },
    ]
  },
  {
    id: 'composition',
    title: 'ترکیب‌بندی (Composition)',
    type: 'simple',
    options: [
      { label: 'قانون یک‌سوم', value: 'rule of thirds composition', description: 'قرار دادن عناصر کلیدی در امتداد خطوط یا در محل تقاطع آن‌ها برای ایجاد تعادل.' },
      { label: 'متقارن', value: 'symmetrical composition', description: 'چیدمان عناصر به گونه‌ای که دو طرف کادر آینه‌ی یکدیگر باشند.' },
      { label: 'نامتقارن', value: 'asymmetrical composition', description: 'چیدمان نامساوی عناصر که با این حال در تصویر تعادل بصری ایجاد می‌کند.' },
      { label: 'فضای منفی', value: 'negative space composition', description: 'استفاده از فضای خالی اطراف سوژه برای برجسته کردن آن.' },
      { label: 'پیش‌زمینه پویا', value: 'dynamic foreground', description: 'قرار دادن عناصر جالب در پیش‌زمینه برای ایجاد عمق و جذابیت.' },
      { label: 'کادربندی', value: 'framing composition', description: 'استفاده از عناصر محیطی (مانند در یا پنجره) برای ایجاد یک قاب طبیعی دور سوژه.' },
    ],
  },
];